version: '3'
services:
    app:
        build: .
        command: npm start
        ports:
            - 1234:1234
        volumes:
            - ./:/src/
            # - ./nodemodules:/src/node_modules

volumes:
    nodemodules: {}
